apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*nginx*.log
        Parser            nginx_json
        Tag               nginx.*
        Refresh_Interval  5
        Rotate_Wait       30

    [FILTER]
        Name modify
        Match nginx.*
        Rename request_time latency_seconds

    [OUTPUT]
        Name prometheus_exporter
        Match nginx.*
        Add_Label app nginx
        Add_Label deployment nginx
        Add_Timestamp On

  parsers.conf: |
    [PARSER]
        Name        nginx_json
        Format      json
        Time_Key    time_local
        Time_Format %d/%b/%Y:%H:%M:%S %z
