apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fluent-bit-monitor
  namespace: monitoring
  labels:
    release: prometheus  # must match your Prometheus release name
spec:
  selector:
    matchLabels:
      app: fluent-bit
  namespaceSelector:
    matchNames:
      - logging
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
