apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ianflanagan1@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod # Secret for storing the ACME account's private key
    solvers: # Enable the HTTP-01 challenge resolver (recommended for Ingress)
    - http01:
        ingress:
          class: nginx