apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap

  use-forwarded-headers: "true"       # Pass through X-Forwarded-For header instead of overwriting (to keep client's original IP)
  compute-full-forwarded-for: "true"  # Append Ingress IP to X-Forwarded-For instead of overwriting (to keep client's original IP)
  enable-real-ip: "true"              # Use left-most IP in X-Forwarded-For header for $remote_addr (for logs etc.); overwrite/remove the CloudFlare IP

  # Trust CloudFlare IP ranges  https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6
  proxy-real-ip-cidr: "10.42.0.0/16,173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32"

  proxy-set-headers: "ingress-nginx/ingress-custom-headers"  # Namespace/ConfigMap

  # Logs
  error-log-path:  "/proc/self/fd/2"
  access-log-path: "/proc/self/fd/1"
  log-format-upstream: '$request_id $time_iso8601 $request $status $http_x_forwarded_for $http_referer "$http_user_agent"'

  # Brotli
  enable-brotli: "true"
  brotli-level: "4"       # compression level 1-11. 4-6 balances speed/compression
  brotli-min-length: "1280"
  brotli-types: "text/plain text/css application/json application/javascript application/x-javascript application/xml text/xml text/javascript application/rss+xml application/atom+xml application/vnd.ms-fontobject application/font-sfnt application/font-woff application/font-woff2 image/svg+xml"

  # Gzip
  use-gzip: "true"
  gzip-level: "5"         # compression level 1-9. 5-6 balances speed/compression
  gzip-min-length: "1280" # minimum size (bytes) to trigger compression. don't compress below the size of a single packet
  gzip-proxied: "any"     # compress responses for all proxied requests (CDN etc)
  gzip-vary: "on"         # tell proxies to cache different versions for different Accept-Encoding headers (brotli, gzip, none)
  gzip-types: "text/plain text/css application/json application/javascript application/x-javascript application/xml text/xml text/javascript application/rss+xml application/atom+xml application/vnd.ms-fontobject application/font-sfnt application/font-woff application/font-woff2 image/svg+xml"
