prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: prometheus-storage-class
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
