apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: public
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: private
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: metrics
      port: 9113
      targetPort: 9113
