apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-db-seed
  namespace: laravel
spec:
  template:
    spec:
      containers:
        - name: laravel-db-seed
          image: docker.io/ianflanagan1/wh-backend-laravel-prod:latest
          imagePullPolicy: Always
          command: ["php", "artisan", "db:seed", "--force"]
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          envFrom:
            - secretRef:
                name: laravel
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Never
  backoffLimit: 1
