apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: laravel-service-monitor
  namespace: monitoring # same as prometheus
  labels:
    release: prometheus # tells the prometheus operator which Prometheus instance should pick this up. helm install prometheus .....
spec:
  selector:
    matchLabels:
      app: laravel
  endpoints:
    - port: private
      path: /laravel-metrics
      interval: 15s
  namespaceSelector:
    matchNames:
    - laravel
