name: wh

services:
  backend-nginx:
    # image: ianflanagan1/wh-backend-nginx-dev
    build:
      context: ./../backend-laravel
      dockerfile: ./../docker/backend-nginx.Dockerfile
      target: dev
    depends_on:
      laravel:
        condition: service_started
    ports:
      - 8080:8080 # External traffic
      - 8081:8081 # Internal traffic (health checks, prometheus etc.)
    volumes:
      - ./../backend-laravel/public:/usr/share/nginx/static:ro
      - ./../config/dev/backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./../config/dev/backend/nginx/nginx-dev-override.conf:/etc/nginx/conf.d/nginx-dev-override.conf:ro
      - ./../config/dev/backend/nginx/telescope-override.conf:/etc/nginx/conf.d/8080/telescope-override.conf:ro
      - php-fpm-socket:/var/run/php:rw

  laravel:
    # image: ianflanagan1/wh-backend-laravel-dev
    build:
      context: ./../backend-laravel
      dockerfile: ./../docker/backend-laravel.Dockerfile
      target: dev
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    #   postgres-testing:
    #     condition: service_healthy
    #   redis:
    #     condition: service_healthy
    working_dir: /app
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./../backend-laravel:/app:rw
      - ./../config/prod/backend/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./../config/dev/backend/php/php-dev-override.ini:/usr/local/etc/php/conf.d/php-dev-override.ini:ro
      - ./../config/dev/backend/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./../config/prod/backend/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./../tmp/profiles:/tmp/profiles:rw
      - php-fpm-socket:/var/run/php:rw
      # for testing
      - ./../scripts/dev/run_php_tests.sh:/usr/local/bin/run_php_tests.sh

  postgres:
    image: docker.io/library/postgres:17.5-alpine
    healthcheck:
      test: ["CMD-SHELL", "sh", "-c", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 1s
      interval: 1s
      timeout: 1s
      retries: 1
    env_file: ./../backend-laravel/.env
    # ports:
    #   - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw

  postgres-testing:
    image: docker.io/library/postgres:17.5-alpine
    healthcheck:
      test: ["CMD-SHELL", "sh", "-c", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 1s
      interval: 1s
      timeout: 1s
      retries: 1
    env_file: ./../backend-laravel/.env
    ports:
      - 5433:5432
    volumes:
      - postgres-testing-data:/var/lib/postgresql/data:rw

  redis:
    image: docker.io/library/redis:7.4-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 1s
      interval: 1s
      timeout: 1s
      retries: 1
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}"]
    # ports:
    #   - 6379:6379
    volumes:
      - redis-data:/data:rw
      - ./../config/prod/backend/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro

  # frontend-nginx:
  #   # image: ianflanagan1/wh-frontend-dev
  #   build:
  #     context: ./../frontend-vue
  #     dockerfile: ./../docker/frontend.Dockerfile
  #     target: dev
  #   ports:
  #     - 8180:8080
  #     - 8181:8081
  #   volumes:
  #     # - ./../frontend-vue/dist:/usr/share/nginx/static:ro
  #     - ./../config/prod/frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  php-fpm-socket:
  postgres-data:
  postgres-testing-data:
  redis-data:
